### ISSUE TITLE
Problema de visualitzacio

### ISSUE THREAD

**Issue by yannickbf-prog** [yannickbf-prog/Exercicis_disseny_interficies_web#1]
Si borro aquesta linea es descuadra es menu
https://github.com/yannickbf-prog/Exercicis_disseny_interficies_web/blob/a1ba2574f909b3bb5e29f640c44917992ac359d8/e01.1_CSS_Basic/css/styles.css#L67

@classicoman2

**Comment by classicoman2** [comment]
Per que veig, ja ho has arreglat, no? Si és aixi, pots tancar la ISSUE

**Comment by yannickbf-prog** [comment]
Si, ho he arreglat amb el float: left; lo que no acabo d'entendre per que pasa aixo si no poso un float left, crec que en teoria no hauria de pasar pero pasa per alguna rao que deconeguda.
