### ISSUE TITLE
Aqui he tingut que posar un position relative per que no es solapes amb es div d'adalt del nav

### ISSUE THREAD

**Issue by yannickbf-prog** [yannickbf-prog/Exercicis_disseny_interficies_web#2]
No se si ha sigut per posar un position relative aqui o no, pero l'he tengut que emprar varies vegades position relative en altres elements perque s'em solapaven els div o altres elements html

https://github.com/yannickbf-prog/Exercicis_disseny_interficies_web/blob/a1ba2574f909b3bb5e29f640c44917992ac359d8/e01.1_CSS_Basic/css/styles.css#L57

@classicoman2

**Comment by classicoman2** [comment]
Té un comportament ben estrany, aquest <ul>, no entenc per què fa aquestes coses tan estranyes. 
De tota manera, aquests tipus d'errors desapareixeran quan comencem a emprar Flexbox (i puguem prescindir d'aquestes propietats gairebé sempre).

**Comment by yannickbf-prog** [comment]
D'acord..., a mi moltes vegades el html amb ccs em fa coses extanyes, pero aquesta cosa precisament no m'habia pasat mai, es a dir posar un div a sota d'un altre i que s'em solapes el padding. Suposo que empran Flexbox al final no et trobes tant amb problemes aixi com em dius, tambe empran Bootstrap suposo que es mes dificil que tinguis un problema aixi. 

Et volia preguntar una cosa, he vist que has posat el exercici e02.1 Flexbox exercises aquest s'hauria de tenir fet per dimecres?

Que tenguis un bon dia

**Comment by classicoman2** [comment]
Pensa que els exercicis no són obligatoris i que s'han d'anar fent amb vostre ritme.

**Comment by classicoman2** [comment]
Per cert, no oblidis espitjar el botó de **Close Issue** per tancar les incidències, @yannickbf-prog !

**Comment by yannickbf-prog** [comment]
D'acord, es vera... 😅 Ara ho faig

**Comment by yannickbf-prog** [comment]
Tanco issue
